name: Publish

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo clippy -- -D warnings
    - uses: cargo-bins/cargo-binstall@main
    - run: cargo binstall dioxus-cli --version 0.7.9 --locked -y
    - run: dx build --release --debug-symbols false --platform web --base-path web
    - run: cp target/dx/web/release/web/public/index.html target/dx/web/release/web/public/404.html
    - uses: actions/upload-pages-artifact@v3
      with:
        path: target/dx/web/release/web/public/
    - uses: actions/deploy-pages@v4
